### ISSUE TITLE
Unable to init PostgreSQL env

### ISSUE THREAD

**Issue by vkhromenkov** [Senzing/docker-init-container#100]
I'm trying to init docker container for stream-loader as was told by running stream-loader container: 
> senzing-50010567E Postgresql database connection detected but no governor installed. Please install governor or run the senzing-init-container container. Connection strings: ['postgresql://g2user:g2psw@dbhost:5432/G2']

But after running docker container from this project I'm getting: 
> senzing-50070297I Enter {"data_dir": "/opt/senzing/data", "db2dsdriver_cfg_contents": null, "debug": false, "delay_in_seconds": 0, "enable_db2": false, "enable_mssql": false, "enable_mysql": false, "enable_postgresql": false, "engine_configuration_json": null, "etc_dir": "/etc/opt/senzing", "g2_dir": "/opt/senzing/g2", "gid": 1001, "governor_url": "https://raw.githubusercontent.com/Senzing/governor-postgresql-transaction-id/master/senzing_governor.py", "license_base64_encoded": null, "mssql_odbc_ini_contents": null, "program_updated": "2020-11-28", "program_version": "1.6.3", "sleep_time_in_seconds": 0, "start_time": 1610718440.121457, "subcommand": "initialize", "uid": 1001, "update_ini_files": false, "var_dir": "/var/opt/senzing"}
2021-01-15 13:47:20,121 senzing-50070154I /var/opt/senzing/sqlite/G2C.db - Creating file by copying /opt/senzing/g2/resources/templates/G2C.db.template
Traceback (most recent call last):
  File "/app/init-container.py", line 1803, in <module>
    globals()[subcommand_function_name](args)
  File "/app/init-container.py", line 1575, in do_initialize
    copy_files(config)
  File "/app/init-container.py", line 1182, in copy_files
    os.makedirs(os.path.dirname(target_file))
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/opt/senzing/sqlite'

I have provided SENZING_DATABASE_URL_PARAMETER, but, as you can see, it tries to init SQLite db instead of postgres

I'm running on CentOS Linux release 7.9.2009, docker 20.10.2, Senzing 2.3.0.20342 (installed using docker container)

Another preparation step - container senzing/postgresql-client - was completed with the same env variable without any problem

**Comment by docktermj** [comment]
Hi @vkhromenkov !

The `senzing/init-container` currently always performs initialization for the possible use of SQLite.  Our thinking is that for testing or debugging, it's nice to be set up to switch to SQLite for a short time.  This thinking is subject to debate, of course.

References:

1. https://github.com/Senzing/docker-init-container/blob/af73273c35461421c448535ed5dad3ee24b74727/init-container.py#L1128-L1142
2. https://github.com/Senzing/docker-init-container/blob/af73273c35461421c448535ed5dad3ee24b74727/init-container.py#L1167-L1183

Having said that, the issue you are seeing is a permissions issue with the path for `/var/opt/senzing/sqlite`.  You can overcome this by running as an elevated user.   (https://github.com/Senzing/docker-init-container#docker-user)   Specifically User "0", which is root.

Let me know if this is a sufficient answer for you or if there are other concerns you have.

**Comment by vkhromenkov** [comment]
Hi @docktermj !

Thanks for so quick response.

I have run it under user "0" and it worked like a charm.

Thanks again
