### ISSUE TITLE
G2Module.ini constructed incorrectly

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-init-container#104]
An upstream issue first detected in https://github.com/Senzing/senzing-up/issues/34

### Issue*

When `G2Module.ini`  is constructed, it appears to have issues.  Example content:
```
[PIPELINE]
SUPPORTPATH = ${SENZING_DATA_DIR}
CONFIGPATH = ${SENZING_CONFIG_PATH}
RESOURCEPATH = ${SENZING_RESOURCES_DIR}

[SQL]
CONNECTION = sqlite3://na:na@/var/opt/senzing/sqlite/G2C.db
```

The `${xxx}` variables should have paths.

**Comment by jeffadair** [comment]
1.6.5 uses the new templates, but doesn't update them properly since the the template "tokens" changed.

Workaround is to use 1.6.4 for now.
