### ISSUE TITLE
init-container.py does not require a root user

### ISSUE THREAD

**Issue by ivanRylach** [Senzing/docker-init-container#22]
**Is your feature request related to a problem? Please describe.**
A default user for the container is set to `uid=1001`, but when `init-container.py` is actually invoked, user is switched [back to root](https://github.com/Senzing/docker-compose-demo/blob/master/resources/postgresql/docker-compose-kafka-postgresql.yaml#L138).
As soon as this line is removed and invocation is done via default `uid=1001`, script fails.

**Describe the solution you'd like**
When `init-container.py` is invoked with the default user, it should work as expected.

**Describe alternatives you've considered**
We forked `init-container.py` and disabled business logic, which is responsible for files manipulation.

**Additional context**

**Comment by docktermj** [comment]
@ivanRylach Thanks for opening up issue.  I'm looking at it now.

**Comment by docktermj** [comment]
@ivanRylach Since you disabled the logic for file manipulation, what functions did you keep?   I ask because I could make a sub-command (i.e. something besides `init-container.py install`) that would do just what you want.

**Comment by ivanRylach** [comment]
@docktermj 
I disabled only file manipulation
```
    # Manipulate files.

    # copy_files(config)
    # change_file_permissions(config)

    # Change ini files

    # change_module_ini(config)
    # change_project_ini(config)
```

**Comment by docktermj** [comment]
@ivanRylach I've committed a new version of init-container.py that I have successfully run as non-root.   Give it a try and let me know if you bump into anything.

I also created a new subcommand `init-container.py initialize-database` that doesn't do the functions you posted above, but does the rest.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/docker-init-container/pull/23
