### ISSUE TITLE
Fix MS SQL odbc.ini Server value

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-init-container#71]
**Describe the bug**

`odbc.ini` currently has an incorrect format:

```console
[G2]
Database = G2
Description = Senzing MS SQL database for G2
Driver = ODBC Driver 17 for SQL Server
Port = 1433
Server = 10.1.1.113
```
According to https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/connection-string-keywords-and-data-source-names-dsns?view=sql-server-ver15  it should be

```console
[G2]
Database = G2
Description = Senzing MS SQL database for G2
Driver = ODBC Driver 17 for SQL Server
Server = 10.1.1.113,1433
```

**Comment by docktermj** [comment]
Pull requests

1. https://github.com/Senzing/docker-init-container/pull/72

**Comment by jaymuthus** [comment]
@docktermj It worked fine and he was able to install on the next day. I thought you got the update as he replied the same email. Thank you very much for your immediate fix on this.

We can close this ticket now.
