### ISSUE TITLE
Support SENZING_ENGINE_CONFIGURATION_JSON for installing Govenor for PostgreSQL

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-init-container#88]
**Is your feature request related to a problem? Please describe.**
In https://github.com/Senzing/docker-init-container/issues/77, if the URL schema is `postgres://` in the `SENZING_DATABASE_URL`, we import https://raw.githubusercontent.com/Senzing/governor-postgresql-transaction-id/master/senzing_governor.py

We need to have the same support if a PostgreSQL database is seen in `SENZING_ENGINE_CONFIGURATION_JSON`.

**Comment by docktermj** [comment]
Example value for `SENZING_ENGINE_CONFIGURATION_JSON`

```json
        {
        	"PIPELINE": {
        		"CONFIGPATH": "/etc/opt/senzing",
        		"RESOURCEPATH": "/opt/senzing/g2/resources",
        		"SUPPORTPATH": "/opt/senzing/data"
        	},
        	"SQL": {
        		"BACKEND": "HYBRID",
        		"CONNECTION": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST}:5432:${POSTGRES_DB:-G2}"
        	},
        	"C1": {
        		"CLUSTER_SIZE": "1",
        		"DB_1": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST_RES}:5432:${POSTGRES_DB:-G2_RES}"
        	},
        	"C2": {
        		"CLUSTER_SIZE": "1",
        		"DB_1": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST_LIBFEAT}:5432:${POSTGRES_DB:-G2_LIBFEAT}"
        	},
        	"HYBRID": {
        		"RES_FEAT": "C1",
        		"RES_FEAT_EKEY": "C1",
        		"RES_FEAT_LKEY": "C1",
        		"RES_FEAT_STAT": "C1",
        		"LIB_FEAT": "C2",
        		"LIB_FEAT_HKEY": "C2"
        	}
        }
```

**Comment by docktermj** [comment]
Tips for parsing the JSON can be seen at https://github.com/Senzing/docker-init-container/blob/422760953e469d409f2584982aa39ff0fee1f6d7/init-container.py#L984-L1013

**Comment by jeffadair** [comment]
SENZING_ENGINE_CONFIGURATION_JSON has priority over SENZING_DATABASE_URL, so only check SENZING_DATABASE_URL if SENZING_ENGINE_CONFIGURATION_JSON  is not defined.

**Comment by jeffadair** [comment]
While investigating this, I discovered a larger issue that I filed in #89 . To band aid this one, I'll create an ENV VAR only (no command line) to force the governor to install.

**Comment by jeffadair** [comment]
Set SENZING_INSTALL_POSTGRESQL_GOVERNOR to True to force docker-init-container to attempt to install the senzing postgresql governor
