### ISSUE TITLE
When using SENZING_ENGINE_CONFIGURATION_JSON, initialize each database

### ISSUE THREAD

**Issue by jeffadair** [Senzing/docker-init-container#89]
When working on #88 I noticed that the db type specific initialization code was not getting run at all. It was defaulting to sqlite3 and running that.

https://github.com/Senzing/docker-init-container/blob/422760953e469d409f2584982aa39ff0fee1f6d7/init-container.py#L1395-L1423

If SENZING_ENGINE_CONFIGURATION_JSON is specified, then each database needs to be initialized that is specified in HYBRID (only once per instance of course.)

**Comment by jeffadair** [comment]
I also ran into some problems with different formats of the db connection string (backslash vs colon specifically). This code is recommended by Michael to normalize the connection strings. Maybe the code should preprocess the connection strings no matter where they come from and store them, and then use the stored normalized for instead of going to the ENV VARs all the time.

https://github.com/Senzing/senzing-environment/blob/ef51bc6c545a901b0225a7f377f7111804e0bb20/senzing-environment.py#L469-L475

https://github.com/Senzing/senzing-environment/blob/ef51bc6c545a901b0225a7f377f7111804e0bb20/senzing-environment.py#L603-L621

From Michael: Note that the magic is in the parse_string() function (https://github.com/Senzing/senzing-environment/blob/ef51bc6c545a901b0225a7f377f7111804e0bb20/senzing-environment.py#L573-L600)

**Comment by docktermj** [comment]
Some code that shows how to parse `SENZING_ENGINE_CONFIGURATION_JSON`:

https://github.com/Senzing/governor-postgresql-transaction-id/blob/4e192587ee52196ef2ce7f58447c9eaae9aec42f/senzing_governor.py#L130-L143

**Comment by docktermj** [comment]
In https://github.com/Senzing/docker-init-container/pull/96 added ability to pull out database scheme from `SENZING_ENGINE_CONFIGURATION_JSON` and verify that all databases in `SENZING_ENGINE_CONFIGURATION_JSON` are the same scheme.

This means that the correct `database_initialization_XXXXX` routine will be called based on the schema.   However, the work done in the pull request did not modify the `database_initialization_XXXXX` routines.  For instance, the creating of `odbc.ini` and `odbcinst.ini` files have not been updated to account for multiple databases.  So this work still needs to be done.
